language: python
python:
  - "3.6.1"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - pytest test.py
deploy:
  provider: Heroku
  api_key: 
    secure: vZaYTCw4o+myWU1Pq8VkNf50Bg0sYQeTt6LEz4aIO/5Wezbpft6nTJd3oncT5O/iwLXZEFfgw5+8xADOrML7vTeW8FZU3Z/YeOmo0DD6y5QKc2bkfGA1FjVcwE5JNktwhmnagvJjUpIEiadXkJKBf7ZayTZ8mn4QMrZttwk/5duB+DHcaYgWrMrkHagLoo3rB/svRYM9u0bYyuZUvlE8MyWxvw3VFOxlKXoyXrYX/SZE04spRsn8G7Al1yhYwWajsyn3+il3PgatuSq9eBLikvq/7QFxsfHZrcdjQJuAcv4TTn1QBVEk4HxUN7oSiYBQNWJ/b5nOzGYMLAZRcl8mx8zmLlJqTig8JpXo62anvEeI8sCDwbbLimMlPugHAOBrpyAtEW5IkV7lhY5tKIAe3Uu30ZvHk58b19FCN3frsEfGEnkuKG3Sf84JXLKPUINACJkKqPsC6WyKzwZETKN+53DK3x4GcxKiDl4xmehr5jQw68mOWLCjoMNBX0dFsFEjMdPqO2I79lmExorQA5bI19L1yGhaDAk+M6hpqEAd1kEdp7pburFo7lVe1oMqDu6D3LodM+JP1ZrkR1XXZ8YfoxRyZmw/lGy2rZFg2PtTClZdzYHOzOaUyveWmTFlGvys8hlQovDHqEyAQoR1+UnlZ3gw6siH1fblHhnGz2ZQ3O4=
  app: qatbadmap
