language: python
python:
  - "3.6.1"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - pytest test.py
deploy:
  provider: Heroku
  api_key: 
    secure: PLMTRTXVkdAZGKxRvHCjklZKN7myEy6NSUnEbIe5ZRU8W+xvN439glqm9CJaEg+nvfxCkMKjCcZnsYgaH533Fn/4C0Ayv1KFqvwGKoG0/WgcEfxn2sbacvueDJ21jmrfNuNIc1yYp2GuXeMfog/jA0cTVOMeGWBGdqJhJMLixkw/KBxgcEbI/I6GLngQS/aWcshl+D4tb65b9/hHO/HQeys/ZdKAztqFcpST+6KqLH4qu0HYOtn9ZFdpDNLVh4yC8yQa19nDPsI93sBfWDD7Q2IJwjn7qsWKH7v22AphkQ4w28JtOlstVppq8pKbwEAizMvfvo7zemkBYMe15HwCiGxRPvt+51J1TONna+fbWRHDuOW7sca43bpABJd8V8WQnAUiRtLJ+vZuFpMTOzLuFmW8ZGB0U+oIFL26K8mX87WSxUglCF6+dsExQbh+TY3BnIdiY6/7M6MO86k7KFTn8QR5EaLPvW7XAYauL/9pkhBzg5Orar0qBi3Et76/0fB0DZ09rHywo6cnjCdyA0WetCN3wujJKvYue9+pyNE/0VtABJ+rQiQPYeLmQSu6IVgkniZAWAIQKBzvSY3WFTv/okctWPoMzjruS/KbOxC3DefKV7JY7b/fgrmhj+souNZD3Y4WuJxUbLSDKTWOPiBpbpUrYb0YJwpGpst20odkxIw=
  app: qatbadmap
